config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  patch 'tasks/:id/complete', to: 'tasks#complete', as: :complete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :complete, :destroy]

  def index
    @task = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      redirect_to new_task_path
    end
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def complete
    @task.update(completed: !(@task.completed))
    redirect_to :back
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :deadline)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <br><br>
  <%= f.label :title %>
  <br>
  <%= f.text_field :title %>
  <br><br>
  <%= f.label :description %>
  <br>
  <%= f.text_area :description %>
  <br><br>
  <%= f.label :deadline %>
  <br>
  <%= f.text_field :deadline %>
  <br><br>

  <%= f.submit %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h2>Edit <%= @task.title %></h2>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h2>Your tasks</h2>

<ul>
  <% @task.each do |task| %>
    <li class='completed-<%= task.completed %>'>
      <%= link_to complete_path(task), method: :patch do %>
        <div class='checkbox'></div>
      <% end %>
      <span class="title"><%= link_to task.title, task_path(task) %></span>
      <span class="deadline"><%= task.deadline %></span>
    </li>
  <% end %>
</ul>

<%= link_to "Create a new task", new_task_path %>

app/views/tasks/new.html.erb
<h2>Create new task</h2>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h2 class='completed-<%= @task.completed %>'>
  <%= @task.title %>
  <%= link_to complete_path(@task), method: :patch do %>
    <div class='checkbox'></div>
  <% end %>
</h2>
<h5><%= @task.deadline %></h5>

<p class="menu"><%= link_to "edit", edit_task_path(@task) %> | <%= link_to "delete", task_path(@task), method: :delete %></p>

<p><%= @task.description %></p>

<%= link_to "< Back to tasks", root_path %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>